### PR TITLE
Fixed bug position of possible figure movement. Closed #3

### LINKED ISSUE #3: Position of possible figure movement
Position of possible figure movement by a line higher than the possible one.

### PR DESCRIPTION
**Pull request by HecuseS**

### CODE REVIEW

**Review by Andrey31ts — APPROVED** [review]

**Review by Andrey31ts — APPROVED** [review]

File: GameField.cs [hunk 1]
```diff
@@ -1,5 +1,6 @@
 ﻿using System;
 using System.Collections.Generic;
+using System.Windows.Documents;
```
Comment (TopAcademy2022) [inline GameField.cs:3]: Remove this.

File: GameField.cs [hunk 2]
```diff
@@ -49,31 +50,33 @@ private bool CheckPlayerAccessFigure(uint[] figurePosition)
         }
 
         // True is UP, true is figure start index = 0; false = figure start index is COUNT_ROWS - 1
```
Comment (TopAcademy2022) [inline GameField.cs:52]: Remove this line.

**Review by Andrey31ts — DISMISSED** [review]

**Review by TopAcademy2022 — CHANGES_REQUESTED** [review]

**Review by London3149-train — APPROVED** [review]

**Review by Andrey31ts — APPROVED** [review]

**Review by cany8042 — APPROVED** [review]

**Review by cany8042 — APPROVED** [review]

**Review by cany8042 — APPROVED** [review]

**Review by cany8042 — APPROVED** [review]

**Review by TopAcademy2022 — APPROVED** [review]

**Review by Mi-stik31 — APPROVED** [review]

**Review by SugarSalt9 — APPROVED** [review]
